### PR TITLE
cleanup: run `npx prettier -w .`

### PR DESCRIPTION
**Pull request by Jolg42**
✨

### CODE REVIEW

**Comment by mrchrisadams** [comment]
Thanks for this Joel!

Have you got this set up on any of your projects via eslint with some `eslintrc`, or `prettierrc` file?

It would be good to have this as a pre-commit hook, or something similar, so that this can be run as a part of usual workflow.

I have something like this on another project here:

https://github.com/Greening-Digital/constellate/blob/master/cl8-web/.eslintrc.js

Would you mind adding this prettier as a dev dependency or something similar for this PR?

**Comment by Jolg42** [comment]
Done in latest commit but now eslint is not super happy 😅 

```
/Users/j42/Sites/grid-intensity/src/browser.bundle.js
  4:1  error  'window' is not defined  no-undef

/Users/j42/Sites/grid-intensity/src/browser.js
   3:33  error  'fetch' is not defined         no-undef
   4:40  error  'localStorage' is not defined  no-undef
  14:19  error  'fetch' is not defined         no-undef

/Users/j42/Sites/grid-intensity/src/gridIntensity.js
   9:49  error  'localStorage' is defined but never used  no-unused-vars
   9:63  error  'fetch' is defined but never used         no-unused-vars
  31:5   error  'parsedIntervals' is not defined          no-undef
  33:7   error  'parsedIntervals' is not defined          no-undef
  35:12  error  'parsedIntervals' is not defined          no-undef

/Users/j42/Sites/grid-intensity/src/index.test.js
   15:42  error    'x' is defined but never used                no-unused-vars
   26:42  error    'x' is defined but never used                no-unused-vars
   38:45  error    'x' is defined but never used                no-unused-vars
   50:5   warning  Test has no assertions                       jest/expect-expect
   53:45  error    'x' is defined but never used                no-unused-vars
   64:45  error    'x' is defined but never used                no-unused-vars
   77:42  error    'x' is defined but never used                no-unused-vars
   93:42  error    'x' is defined but never used                no-unused-vars
  147:5   warning  Test has no assertions                       jest/expect-expect
  151:13  error    'result' is assigned a value but never used  no-unused-vars
```

**Comment by mrchrisadams** [comment]
Thanks Joel 👍 

I'm more comfortable in python than node, and I'm not sure of the idiomatic way to account for objects that are provided by the browser window. How should I fix them?

I'm totally down to make a separate issue for that, and then accept this PR, as it's already an improvement on what we had before.

**Comment by Jolg42** [comment]
I tried something with fetch and localstorage, takes a ridiculous amount of time to get something working but it works 😅

**Pull request closed without merging**
